---
# Install/setup common tools and utilities

- name: Common
  hosts: all
  become: true
  vars:
    common_packages:
      - htop
      - vim
      - ncdu
      - tcpdump
      - iotop
      - nmap
    common_packages_os_family:
      Suse:
        - bind-utils
      RedHat:
        - bind-utils
      Debian:
        - bind9-utils
    common_services:
      - sysstat
    common_services_os_family:
      Suse:
        - acct
      RedHat:
        - psacct
      Debian:
        - acct

  tasks:
    - name: Suse operations
      when: ansible_os_family == "Suse"
      block:
        - name: Suse - Install common Linux utilities
          community.general.zypper:
            name: "{{ item }}"
            state: present
          loop:
            - "{{ common_packages }}"
            - "{{ common_packages_os_family[ansible_os_family] }}"

        - name: Suse - Install common services
          community.general.zypper:
            name: "{{ item }}"
            state: present
          loop:
            - "{{ common_services }}"
            - "{{ common_services_os_family[ansible_os_family] }}"

    # TODO: Add support for RedHat

    - name: Debian operations
      when: ansible_os_family == "Debian"
      block:
        - name: Debian - Install common Linux utilities
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop:
            - "{{ common_packages }}"
            - "{{ common_packages_os_family[ansible_os_family] }}"

        - name: Debian - Install common services
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop:
            - "{{ common_services }}"
            - "{{ common_services_os_family[ansible_os_family] }}"

    - name: Enable common services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: >-
        {{ common_services +
        common_services_os_family[ansible_os_family] }}
