---
# Install/setup common tools and utilities

- name: Common
  hosts: all
  become: true
  vars:
    common_packages:
      - htop
      - vim
    common_sysstat: true

  tasks:
    - name: Suse operations
      when: ansible_os_family == "Suse"
      block:
        - name: Suse - Install Linux utilities
          community.general.zypper:
            name: "{{ common_packages }}"
            state: present

        - name: Suse - Install sysstat
          community.general.zypper:
            name: sysstat
            state: present
          when: common_sysstat
          notify: Enable sysstat

    - name: Debian operations
      when: ansible_os_family == "Debian"
      block:
        - name: Debian - Install Linux utilities
          ansible.builtin.apt:
            name: "{{ common_packages }}"
            state: present

        - name: Debian - Install sysstat
          ansible.builtin.apt:
            name: sysstat
            state: present
          when: common_sysstat
          notify: Enable sysstat

  handlers:
    - name: Enable sysstat
      ansible.builtin.systemd:
        name: sysstat
        state: started
        enabled: true
