---
# Onboard new hosts

- name: Bootstrap
  ansible.builtin.import_playbook: playbooks/bootstrap.yml
  vars:
    ansible_user: root

- name: Set hostname
  ansible.builtin.import_playbook: playbooks/hostname.yml
  vars:
    hostname_reboot: false

- name: Set timezone
  ansible.builtin.import_playbook: playbooks/timezone.yml

- name: Create swap
  ansible.builtin.import_playbook: playbooks/swap.yml

- name: Update host
  ansible.builtin.import_playbook: playbooks/update.yml

- name: Install common tools
  ansible.builtin.import_playbook: playbooks/common.yml
