---
# Setup Proxmox VE host

- name: Proxmox
  hosts: all

  tasks:
    - name: Remove pve-enterprise repo
      ansible.builtin.apt_repository:
        repo: deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
        state: absent

    - name: Add pve-no-subscription repo
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        state: present
