---
# Install/setup common tools and utilities

- name: Common
  hosts: all
  become: true
  vars:
    # Packages common to all (most) Linux distros
    # See: https://www.cyberciti.biz/tips/top-linux-monitoring-tools.html
    common_packages:
      - htop
      - iotop
      - iftop
      - nmon
      - nmap
      - telnet
      - tcpdump
      - strace
      - vim
      - ncdu
      - tree
    # Packages common to all (most) Linux distros but that have different
    # package names depending on which OS family it's from.
    common_packages_os_family:
      Suse:
        - bind-utils
        - openscap-utils
      RedHat:
        - bind-utils
        - openscap-utils
      Debian:
        - bind9-utils
        - libopenscap8
    # Services common to all (most) Linux distros
    common_services:
      - sysstat
    # Services common to all (most) Linux distros but that have different
    # package names depending on which OS family it's from.
    # yamllint disable-line rule:line-length
    # See: https://www.cyberciti.biz/tips/howto-log-user-activity-using-process-accounting.html
    common_services_os_family:
      Suse:
        - acct
      RedHat:
        - psacct
      Debian:
        - acct

  tasks:
    - name: Suse operations
      when: ansible_os_family == "Suse"
      block:
        - name: Suse - Install common Linux utilities
          community.general.zypper:
            name: "{{ item }}"
            state: present
          loop:
            - "{{ common_packages }}"
            - "{{ common_packages_os_family[ansible_os_family] }}"

        - name: Suse - Install common services
          community.general.zypper:
            name: "{{ item }}"
            state: present
          loop:
            - "{{ common_services }}"
            - "{{ common_services_os_family[ansible_os_family] }}"

    # TODO: Add support for RedHat

    - name: Debian operations
      when: ansible_os_family == "Debian"
      block:
        - name: Debian - Install common Linux utilities
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop:
            - "{{ common_packages }}"
            - "{{ common_packages_os_family[ansible_os_family] }}"

        - name: Debian - Install common services
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop:
            - "{{ common_services }}"
            - "{{ common_services_os_family[ansible_os_family] }}"

    - name: Enable common services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: >-
        {{ common_services +
        common_services_os_family[ansible_os_family] }}
